remove py33 from travis config
When testing under py33, travis will raise error below:

    ERROR: unknown environment 'py33'

It seems py33 is not supported in the latest tox, or whatever the reason,
this is a CI environment problem. Besides, python 3.3 is too old
to have value for testing nowadays.